### ISSUE TITLE
i am not saying ur code is wrong this is what happened

### ISSUE THREAD

**Issue by mmk687** [jm33-m0/massExpConsole#24] opened 2018-01-04 12:59 UTC
i installed the code again, i git bull, i used verified account, i think i miss one of the indepencies,
what is ur openion
[Screencast_01-03-2018_12^%23^%58 AM.zip](https://github.com/jm33-m0/massExpConsole/files/1599457/Screencast_01-03-2018_12.23.58.AM.zip)

[Screencast_01-02-2018_11^%42^%30 PM.zip](https://github.com/jm33-m0/massExpConsole/files/1599426/Screencast_01-02-2018_11.42.30.PM.zip)
[Screencast_01-02-2018_11^%56^%26 PM.zip](https://github.com/jm33-m0/massExpConsole/files/1599427/Screencast_01-02-2018_11.56.26.PM.zip)

  [Screencast_01-03-2018_12^%23^%58 AM.zip](https://github.com/jm33-m0/massExpConsole/files/1599458/Screencast_01-03-2018_12.23.58.AM.zip)

**Comment by jm33-m0** [comment] 2018-01-04 15:16
- don't post zip archives, use screenshots instead
- stop opening new issues unless you have a new bug to report, otherwise you will be considered a **spammer**
- use **meaningful** titles
- since your error can't be reproduced, i am closing this issue

**Closed by jm33-m0** 2018-01-04 15:16 UTC
